//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Services.Token {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Services.Token.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token didn&apos;t pass verification because {0}..
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormat {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id claim is not a number.
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonIdBadFormat {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonIdBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id claim does not exist.
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonIdMissing {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other error, see inner exception for information.
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonOthers {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error.
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonUnknown {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version claim is not a number..
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonVersionBadFormat {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonVersionBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version claim does not exist..
        /// </summary>
        internal static string ExceptionJwtUserTokenBadFormatReasonVersionMissing {
            get {
                return ResourceManager.GetString("ExceptionJwtUserTokenBadFormatReasonVersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is of bad format, which means it may not be created by the server..
        /// </summary>
        internal static string ExceptionUserTokenBadFormat {
            get {
                return ResourceManager.GetString("ExceptionUserTokenBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is expired because its expiration time has passed..
        /// </summary>
        internal static string ExceptionUserTokenTimeExpired {
            get {
                return ResourceManager.GetString("ExceptionUserTokenTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner user of the token does not exist..
        /// </summary>
        internal static string ExceptionUserTokenUserNotExist {
            get {
                return ResourceManager.GetString("ExceptionUserTokenUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is of bad version..
        /// </summary>
        internal static string ExceptionUserTokenVersionExpired {
            get {
                return ResourceManager.GetString("ExceptionUserTokenVersionExpired", resourceCulture);
            }
        }
    }
}
