//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Services.Exception", typeof(Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrong..
        /// </summary>
        internal static string BadPasswordException {
            get {
                return ResourceManager.GetString("BadPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the jwt token is old..
        /// </summary>
        internal static string JwtBadVersionException {
            get {
                return ResourceManager.GetString("JwtBadVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token didn&apos;t pass verification because {0}, see inner exception for information..
        /// </summary>
        internal static string JwtVerifyException {
            get {
                return ResourceManager.GetString("JwtVerifyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token is expired..
        /// </summary>
        internal static string JwtVerifyExceptionExpired {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id claim is not a number..
        /// </summary>
        internal static string JwtVerifyExceptionIdClaimBadFormat {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionIdClaimBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id claim does not exist..
        /// </summary>
        internal static string JwtVerifyExceptionNoIdClaim {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionNoIdClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version claim does not exist..
        /// </summary>
        internal static string JwtVerifyExceptionNoVersionClaim {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionNoVersionClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version of token is old..
        /// </summary>
        internal static string JwtVerifyExceptionOldVersion {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncommon error..
        /// </summary>
        internal static string JwtVerifyExceptionOthers {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error code..
        /// </summary>
        internal static string JwtVerifyExceptionUnknown {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version claim is not a number..
        /// </summary>
        internal static string JwtVerifyExceptionVersionClaimBadFormat {
            get {
                return ResourceManager.GetString("JwtVerifyExceptionVersionClaimBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is of bad format..
        /// </summary>
        internal static string UsernameBadFormatException {
            get {
                return ResourceManager.GetString("UsernameBadFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username already exists..
        /// </summary>
        internal static string UsernameConfictException {
            get {
                return ResourceManager.GetString("UsernameConfictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        internal static string UserNotExistException {
            get {
                return ResourceManager.GetString("UserNotExistException", resourceCulture);
            }
        }
    }
}
