//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimelineService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimelineService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Services.TimelineService", typeof(TimelineService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} username is invalid..
        /// </summary>
        internal static string ExceptionChangeMemberUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionChangeMemberUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown post content type &quot;{0}&quot; is saved in database..
        /// </summary>
        internal static string ExceptionDatabaseUnknownContentType {
            get {
                return ResourceManager.GetString("ExceptionDatabaseUnknownContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner username of personal timeline is of bad format..
        /// </summary>
        internal static string ExceptionFindTimelineUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionFindTimelineUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data entry of the tag of the image post does not exist..
        /// </summary>
        internal static string ExceptionGetDataDataEntryNotExist {
            get {
                return ResourceManager.GetString("ExceptionGetDataDataEntryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get data of a non-image post..
        /// </summary>
        internal static string ExceptionGetDataNonImagePost {
            get {
                return ResourceManager.GetString("ExceptionGetDataNonImagePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeline name is of bad format because {0}..
        /// </summary>
        internal static string ExceptionTimelineNameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionTimelineNameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeline with given name already exists..
        /// </summary>
        internal static string ExceptionTimelineNameConflict {
            get {
                return ResourceManager.GetString("ExceptionTimelineNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format type of the post does not exist in column &quot;extra_content&quot;. Normally this couldn&apos;t be possible because it should be saved when post was created. However, we now re-detect the format and save it..
        /// </summary>
        internal static string LogGetDataNoFormat {
            get {
                return ResourceManager.GetString("LogGetDataNoFormat", resourceCulture);
            }
        }
    }
}
