//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelineApp.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimelineApp.Resources.Services.UserService", typeof(UserService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New username is of bad format..
        /// </summary>
        internal static string ExceptionNewUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionNewUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname is of bad format, because {}..
        /// </summary>
        internal static string ExceptionNicknameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionNicknameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old username is of bad format..
        /// </summary>
        internal static string ExceptionOldUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionOldUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty..
        /// </summary>
        internal static string ExceptionPasswordEmpty {
            get {
                return ResourceManager.GetString("ExceptionPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be null..
        /// </summary>
        internal static string ExceptionPasswordNull {
            get {
                return ResourceManager.GetString("ExceptionPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is of bad format, because {}..
        /// </summary>
        internal static string ExceptionUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with given username already exists..
        /// </summary>
        internal static string ExceptionUsernameConflict {
            get {
                return ResourceManager.GetString("ExceptionUsernameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be null..
        /// </summary>
        internal static string ExceptionUsernameNull {
            get {
                return ResourceManager.GetString("ExceptionUsernameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new user entry is added to the database..
        /// </summary>
        internal static string LogDatabaseCreate {
            get {
                return ResourceManager.GetString("LogDatabaseCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user entry is removed from the database..
        /// </summary>
        internal static string LogDatabaseRemove {
            get {
                return ResourceManager.GetString("LogDatabaseRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user entry is updated to the database..
        /// </summary>
        internal static string LogDatabaseUpdate {
            get {
                return ResourceManager.GetString("LogDatabaseUpdate", resourceCulture);
            }
        }
    }
}
