//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Services.Imaging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Services.Imaging.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is in valid because {0}..
        /// </summary>
        internal static string ExceptionImage {
            get {
                return ResourceManager.GetString("ExceptionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not of required size.
        /// </summary>
        internal static string ExceptionImageReasonBadSize {
            get {
                return ResourceManager.GetString("ExceptionImageReasonBadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to decode image, see inner exception.
        /// </summary>
        internal static string ExceptionImageReasonCantDecode {
            get {
                return ResourceManager.GetString("ExceptionImageReasonCantDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error.
        /// </summary>
        internal static string ExceptionImageReasonUnknownError {
            get {
                return ResourceManager.GetString("ExceptionImageReasonUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image&apos;s actual mime type is not the specified one.
        /// </summary>
        internal static string ExceptionImageReasonUnmatchedFormat {
            get {
                return ResourceManager.GetString("ExceptionImageReasonUnmatchedFormat", resourceCulture);
            }
        }
    }
}
