//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Services.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Services.User.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong..
        /// </summary>
        internal static string ExceptionBadPassword {
            get {
                return ResourceManager.GetString("ExceptionBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change root user&apos;s permission..
        /// </summary>
        internal static string ExceptionChangeRootUserPermission {
            get {
                return ResourceManager.GetString("ExceptionChangeRootUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete root user..
        /// </summary>
        internal static string ExceptionDeleteRootUser {
            get {
                return ResourceManager.GetString("ExceptionDeleteRootUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hashes password is of bad format. It might not be created by server. Reason: {0}.
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormat {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded hashed password is of length 0..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonLength0 {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonLength0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not of valid base64 format. See inner exception..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonNotBase64 {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonNotBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See inner exception..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonOthers {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt length &lt; 128 bits..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonSaltTooShort {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonSaltTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkey length &lt; 128 bits..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonSubkeyTooShort {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonSubkeyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format marker..
        /// </summary>
        internal static string ExceptionHashedPasswordBadFormatReasonUnknownMarker {
            get {
                return ResourceManager.GetString("ExceptionHashedPasswordBadFormatReasonUnknownMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform such operation on root user..
        /// </summary>
        internal static string ExceptionInvalidOperationOnRootUser {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationOnRootUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname is of bad format. {0}.
        /// </summary>
        internal static string ExceptionNicknameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionNicknameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty..
        /// </summary>
        internal static string ExceptionPasswordEmpty {
            get {
                return ResourceManager.GetString("ExceptionPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be null..
        /// </summary>
        internal static string ExceptionPasswordNull {
            get {
                return ResourceManager.GetString("ExceptionPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with given constraints already exists..
        /// </summary>
        internal static string ExceptionUserAlreadyExist {
            get {
                return ResourceManager.GetString("ExceptionUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is of bad format. {0}.
        /// </summary>
        internal static string ExceptionUsernameBadFormat {
            get {
                return ResourceManager.GetString("ExceptionUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be null..
        /// </summary>
        internal static string ExceptionUsernameNull {
            get {
                return ResourceManager.GetString("ExceptionUsernameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested user does not exist..
        /// </summary>
        internal static string ExceptionUserNotExist {
            get {
                return ResourceManager.GetString("ExceptionUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username = {0}, id ={1} changed password..
        /// </summary>
        internal static string LogChangePassowrd {
            get {
                return ResourceManager.GetString("LogChangePassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is deleted with username = {0}, id = {1}..
        /// </summary>
        internal static string LogDeleteUser {
            get {
                return ResourceManager.GetString("LogDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new user is created with username = {0}, id = {1}..
        /// </summary>
        internal static string LogUserCreated {
            get {
                return ResourceManager.GetString("LogUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is modified with username = {0}, id = {1}..
        /// </summary>
        internal static string LogUserModified {
            get {
                return ResourceManager.GetString("LogUserModified", resourceCulture);
            }
        }
    }
}
