# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  ASPNETCORE_ENVIRONMENT: 'Development'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    feedsToUse: config
    nugetConfigPath: nuget.config


- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: Timeline/Timeline.csproj

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'timeline'
    targetPath: Timeline/bin/Release/netcoreapp2.2/publish/
