# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  ASPNETCORE_ENVIRONMENT: 'Development'

steps:
- script: dotnet build --configuration $(buildConfiguration) --configfile nuget.config

- script: dotnet test Timeline.Tests --configuration $(buildConfiguration) --logger trx

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'

- script: dotnet publish Timeline/Timeline.csproj --configuration $(buildConfiguration) --output ./publish/

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'timeline'
    targetPath: Timeline/publish
