//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimelineController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimelineController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Controllers.TimelineController", typeof(TimelineController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown timeline visibility value. Can&apos;t convert it..
        /// </summary>
        internal static string ExceptionStringToVisibility {
            get {
                return ResourceManager.GetString("ExceptionStringToVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown TimelineMemberOperationUserException is thrown. Can&apos;t recognize its inner exception. It is rethrown..
        /// </summary>
        internal static string LogUnknownTimelineMemberOperationUserException {
            get {
                return ResourceManager.GetString("LogUnknownTimelineMemberOperationUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}-st username to do operation {1} on is of bad format..
        /// </summary>
        internal static string MessageMemberUsernameBadFormat {
            get {
                return ResourceManager.GetString("MessageMemberUsernameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}-st user to do operation {1} on does not exist..
        /// </summary>
        internal static string MessageMemberUserNotExist {
            get {
                return ResourceManager.GetString("MessageMemberUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to create posts in the timeline..
        /// </summary>
        internal static string MessagePostsCreateForbid {
            get {
                return ResourceManager.GetString("MessagePostsCreateForbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to read posts of the timeline..
        /// </summary>
        internal static string MessagePostsGetForbid {
            get {
                return ResourceManager.GetString("MessagePostsGetForbid", resourceCulture);
            }
        }
    }
}
