//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Controllers.TokenController", typeof(TokenController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrong..
        /// </summary>
        public static string LogBadPassword {
            get {
                return ResourceManager.GetString("LogBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user failed to create a token..
        /// </summary>
        public static string LogCreateFailure {
            get {
                return ResourceManager.GetString("LogCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user succeeded to create a token..
        /// </summary>
        public static string LogCreateSuccess {
            get {
                return ResourceManager.GetString("LogCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        public static string LogUserNotExist {
            get {
                return ResourceManager.GetString("LogUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is of bad format. It might not be created by the server..
        /// </summary>
        public static string LogVerifyBadFormat {
            get {
                return ResourceManager.GetString("LogVerifyBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is expired..
        /// </summary>
        public static string LogVerifyExpire {
            get {
                return ResourceManager.GetString("LogVerifyExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token failed to be verified..
        /// </summary>
        public static string LogVerifyFailure {
            get {
                return ResourceManager.GetString("LogVerifyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has an old version. User might have update some info..
        /// </summary>
        public static string LogVerifyOldVersion {
            get {
                return ResourceManager.GetString("LogVerifyOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token succeeded to be verified..
        /// </summary>
        public static string LogVerifySuccess {
            get {
                return ResourceManager.GetString("LogVerifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist. Administrator might have deleted this user..
        /// </summary>
        public static string LogVerifyUserNotExist {
            get {
                return ResourceManager.GetString("LogVerifyUserNotExist", resourceCulture);
            }
        }
    }
}
