//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Controllers.UserController", typeof(UserController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong..
        /// </summary>
        internal static string ErrorChangePasswordBadPassword {
            get {
                return ResourceManager.GetString("ErrorChangePasswordBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new username {0} already exists..
        /// </summary>
        internal static string ErrorChangeUsernameAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorChangeUsernameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old username {0} does not exist..
        /// </summary>
        internal static string ErrorChangeUsernameNotExist {
            get {
                return ResourceManager.GetString("ErrorChangeUsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        internal static string ErrorGetUserNotExist {
            get {
                return ResourceManager.GetString("ErrorGetUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t patch a user that does not exist..
        /// </summary>
        internal static string ErrorPatchUserNotExist {
            get {
                return ResourceManager.GetString("ErrorPatchUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is of bad format..
        /// </summary>
        internal static string ErrorPutBadUsername {
            get {
                return ResourceManager.GetString("ErrorPutBadUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to change password with wrong old password failed..
        /// </summary>
        internal static string LogChangePasswordBadPassword {
            get {
                return ResourceManager.GetString("LogChangePasswordBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has changed password..
        /// </summary>
        internal static string LogChangePasswordSuccess {
            get {
                return ResourceManager.GetString("LogChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to change a user&apos;s username to a existent one failed..
        /// </summary>
        internal static string LogChangeUsernameAlreadyExist {
            get {
                return ResourceManager.GetString("LogChangeUsernameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to change a username of a user that does not exist failed..
        /// </summary>
        internal static string LogChangeUsernameNotExist {
            get {
                return ResourceManager.GetString("LogChangeUsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has changed username..
        /// </summary>
        internal static string LogChangeUsernameSuccess {
            get {
                return ResourceManager.GetString("LogChangeUsernameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has been deleted..
        /// </summary>
        internal static string LogDeleteDelete {
            get {
                return ResourceManager.GetString("LogDeleteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete a user that does not exist..
        /// </summary>
        internal static string LogDeleteNotExist {
            get {
                return ResourceManager.GetString("LogDeleteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve info of a user that does not exist failed..
        /// </summary>
        internal static string LogGetUserNotExist {
            get {
                return ResourceManager.GetString("LogGetUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to patch a user that does not exist failed..
        /// </summary>
        internal static string LogPatchUserNotExist {
            get {
                return ResourceManager.GetString("LogPatchUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a user with bad username failed..
        /// </summary>
        internal static string LogPutBadUsername {
            get {
                return ResourceManager.GetString("LogPutBadUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has been created..
        /// </summary>
        internal static string LogPutCreate {
            get {
                return ResourceManager.GetString("LogPutCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has been modified..
        /// </summary>
        internal static string LogPutModify {
            get {
                return ResourceManager.GetString("LogPutModify", resourceCulture);
            }
        }
    }
}
