//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Resources.Models.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Resources.Models.Http.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body is too big. It can&apos;t be bigger than {0}..
        /// </summary>
        internal static string MessageContentTooBig {
            get {
                return ResourceManager.GetString("MessageContentTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual body length is bigger than it in header..
        /// </summary>
        internal static string MessageContentUnmatchedLengthBigger {
            get {
                return ResourceManager.GetString("MessageContentUnmatchedLengthBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual body length is smaller than it in header..
        /// </summary>
        internal static string MessageContentUnmatchedLengthSmaller {
            get {
                return ResourceManager.GetString("MessageContentUnmatchedLengthSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existent item is deleted..
        /// </summary>
        internal static string MessageDeleteDelete {
            get {
                return ResourceManager.GetString("MessageDeleteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item does not exist, so nothing is changed..
        /// </summary>
        internal static string MessageDeleteNotExist {
            get {
                return ResourceManager.GetString("MessageDeleteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header If-Non-Match is of bad format..
        /// </summary>
        internal static string MessageHeaderBadIfNonMatch {
            get {
                return ResourceManager.GetString("MessageHeaderBadIfNonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Content-Length is missing or of bad format..
        /// </summary>
        internal static string MessageHeaderMissingContentLength {
            get {
                return ResourceManager.GetString("MessageHeaderMissingContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Content-Type is required..
        /// </summary>
        internal static string MessageHeaderMissingContentType {
            get {
                return ResourceManager.GetString("MessageHeaderMissingContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Content-Length must not be 0..
        /// </summary>
        internal static string MessageHeaderZeroContentLength {
            get {
                return ResourceManager.GetString("MessageHeaderZeroContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new item is created..
        /// </summary>
        internal static string MessagePutCreate {
            get {
                return ResourceManager.GetString("MessagePutCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existent item is modified..
        /// </summary>
        internal static string MessagePutModify {
            get {
                return ResourceManager.GetString("MessagePutModify", resourceCulture);
            }
        }
    }
}
