//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Auth.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identitifier claim is of bad format..
        /// </summary>
        internal static string ExceptionUserIdentifierClaimBadFormat {
            get {
                return ResourceManager.GetString("ExceptionUserIdentifierClaimBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is found in authorization header. Token is {0} ..
        /// </summary>
        internal static string LogTokenFoundInHeader {
            get {
                return ResourceManager.GetString("LogTokenFoundInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is found in query param with key &quot;{0}&quot;. Token is {1} ..
        /// </summary>
        internal static string LogTokenFoundInQuery {
            get {
                return ResourceManager.GetString("LogTokenFoundInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jwt token is found..
        /// </summary>
        internal static string LogTokenNotFound {
            get {
                return ResourceManager.GetString("LogTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jwt token validation failed. Error reason: {0}.
        /// </summary>
        internal static string LogTokenValidationFail {
            get {
                return ResourceManager.GetString("LogTokenValidationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use a token to authenticate to access this resource..
        /// </summary>
        internal static string MessageNoToken {
            get {
                return ResourceManager.GetString("MessageNoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is of bad format. It might not be created by this server..
        /// </summary>
        internal static string MessageTokenBadFormat {
            get {
                return ResourceManager.GetString("MessageTokenBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is out of date and expired. Please create a new one..
        /// </summary>
        internal static string MessageTokenTimeExpired {
            get {
                return ResourceManager.GetString("MessageTokenTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unknown error occured when verify token..
        /// </summary>
        internal static string MessageTokenUnknownError {
            get {
                return ResourceManager.GetString("MessageTokenUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of the token does not exist. It might have been deleted..
        /// </summary>
        internal static string MessageTokenUserNotExist {
            get {
                return ResourceManager.GetString("MessageTokenUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is of old version and expired. Please create a new one..
        /// </summary>
        internal static string MessageTokenVersionExpired {
            get {
                return ResourceManager.GetString("MessageTokenVersionExpired", resourceCulture);
            }
        }
    }
}
