//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Models.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Models.Validation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it can&apos;t be null.
        /// </summary>
        internal static string CantBeNull {
            get {
                return ResourceManager.GetString("CantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name can&apos;t be empty.
        /// </summary>
        internal static string NameCantBeEmpty {
            get {
                return ResourceManager.GetString("NameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name can&apos;t be longer than {0}.
        /// </summary>
        internal static string NameCantBeLongerThan {
            get {
                return ResourceManager.GetString("NameCantBeLongerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name can&apos;t has the same pattern of unique id.
        /// </summary>
        internal static string NameCantBeUniqueIdPattern {
            get {
                return ResourceManager.GetString("NameCantBeUniqueIdPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name can only consists of alphabet, number, &apos;_&apos; and &apos;-&apos; .
        /// </summary>
        internal static string NameInvalidChar {
            get {
                return ResourceManager.GetString("NameInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nickname can&apos;t be longer than 25.
        /// </summary>
        internal static string NicknameTooLong {
            get {
                return ResourceManager.GetString("NicknameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is not of type {0}.
        /// </summary>
        internal static string NotOfType {
            get {
                return ResourceManager.GetString("NotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create validator instance..
        /// </summary>
        internal static string ValidateWithAttributeExceptionCreateFail {
            get {
                return ResourceManager.GetString("ValidateWithAttributeExceptionCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given type is not a IValidator instance..
        /// </summary>
        internal static string ValidateWithAttributeExceptionNotValidator {
            get {
                return ResourceManager.GetString("ValidateWithAttributeExceptionNotValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation passed.
        /// </summary>
        internal static string ValidationPassed {
            get {
                return ResourceManager.GetString("ValidationPassed", resourceCulture);
            }
        }
    }
}
