pipeline {
  agent {
    docker {
      reuseNode true
      registryUrl 'https://coding-public-docker.pkg.coding.net'
      image 'public/docker/nodejs:14'
    }

  }
  stages {
    stage('检出') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: env.GIT_BUILD_REF]],
          userRemoteConfigs: [[
            url: env.GIT_REPO_URL,
            credentialsId: env.CREDENTIALS_ID
          ]]])
        }
      }
      stage('安装依赖') {
        steps {
          sh 'yarn'
        }
      }
      stage('构建和Lint') {
        parallel {
          stage('构建') {
            steps {
              sh 'yarn build'
            }
          }
          stage('Lint') {
            steps {
              sh 'yarn lint'
            }
          }
        }
      }
    }
    environment {
      YARN_NPM_REGISTRY_SERVER = 'https://registry.npm.taobao.org'
    }
  }