//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeline.Services.DatabaseManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timeline.Services.DatabaseManagement.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup finished with output file at {0}..
        /// </summary>
        internal static string DatabaseBackupServiceFinishBackup {
            get {
                return ResourceManager.GetString("DatabaseBackupServiceFinishBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin custom migration &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseCustomMigratorBeginMigration {
            get {
                return ResourceManager.GetString("DatabaseCustomMigratorBeginMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End custom migration &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseCustomMigratorFinishMigration {
            get {
                return ResourceManager.GetString("DatabaseCustomMigratorFinishMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found custom migration &apos;{0}&apos;. Applied: {1}..
        /// </summary>
        internal static string DatabaseCustomMigratorFoundMigration {
            get {
                return ResourceManager.GetString("DatabaseCustomMigratorFoundMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old image content does not have corresponding data with the tag..
        /// </summary>
        internal static string TimelinePostContentToDataMigrationImageNoData {
            get {
                return ResourceManager.GetString("TimelinePostContentToDataMigrationImageNoData", resourceCulture);
            }
        }
    }
}
