name: Back End CI

on:
  push:
    branches: [main]
    paths:
      - "BackEnd/**"
  pull_request:
    branches: [main]
    paths:
      - "BackEnd/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BackEnd
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('BackEnd/**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Build And Test
        run: dotnet test --logger html --collect:"XPlat Code Coverage" --settings './Timeline.Tests/coverletArgs.runsettings'

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: test-result
          path: BackEnd/Timeline.Tests/TestResults/
