name: CI

on:
  push:
    branches: [dev]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [dev]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Use .Net Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Build And Test
        run: dotnet test --logger html --collect:"XPlat Code Coverage" --settings './Timeline.Tests/coverletArgs.runsettings'

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: test-result
          path: Timeline.Tests/TestResults/
