name: Front End CI

on:
  push:
    branches: [main]
    paths:
      - "FrontEnd/**"
  pull_request:
    branches: [main]
    paths:
      - "FrontEnd/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: FrontEnd

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Restore Packages
        run: pnpm install --frozen-lockfile

      - name: Build App
        run: pnpm run build

      - name: Lint Code
        run: pnpm run lint

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: FrontEnd/dist/
